import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'ko_KR': {
      '로그인': '로그인',
      '회원가입': '회원가입',
      '관리자': '관리자',
      '고용주': '고용주',
      '근로자': '근로자',
      '아이디': '아이디',
      '비밀번호': '비밀번호',
      '본인인증': '본인인증',
      '휴대폰 번호': '휴대폰 번호',
      '인증번호 발송': '인증번호 발송',
      '인증 완료': '인증 완료',
      '관리자 회원가입': '관리자 회원가입',
      '이름': '이름',
      '생년월일': '생년월일',
      '휴대폰 번호(ID)': '휴대폰 번호(ID)',
      '직책': '직책',
      '가입하기': '가입하기',
      '고용주 회원가입': '고용주 회원가입',
      '사업장 위치': '사업장 위치',
      '업장명(상호)': '업장명(상호)',
      '근로자 회원가입': '근로자 회원가입',
      '이메일(ID)': '이메일(ID)',
      '이메일':'이메일',
      '성별': '성별',
      '남자': '남성',
      '여자': '여성',
      '국적': '국적',
      '입국일': '입국일',
      '출국일': '출국일',
      '공지사항': '공지사항',
      '지역별 공지사항': '지역별 공지사항',
      '홈': '홈',
      '로그인/아웃': '로그인/아웃',
      '회사 소개': '회사 소개',
      '홈으로': '홈으로',
      '조직 구성': '조직 구성',
      '출퇴근 QR코드': '출퇴근 QR코드',
      '전체 공지사항': '전체 공지사항',
      '댓글': '댓글',
      '제보하기': '제보하기',
      '제목': '제목',
      '내용': '내용',
      '완료': '완료',
      '제보 글 작성': '제보 글 작성',
      '메세지': '메세지',
      '대화상대 초대': '대화상대 초대',
      '필리핀 식품': '필리핀 식품',
      '교육 정보': '교육 정보',
      '비자 안내': '비자 안내',
      '법률 상담': '법률 상담',
      '도움 전화': '도움 전화',
      '제보하기': '제보하기',
      '필리핀 송금': '필리핀 송금',
      '내 정보': '내 정보',
      '내 정보 수정': '내 정보 수정',
      '근로자 정보': '근로자 정보',
      '고용주 정보': '고용주 정보',
      '출퇴근 현황': '출퇴근 현황',
      '급여 현황': '급여 현황',
      '나의 상세 정보': '나의 상세 정보',
      '출근시간': '출근시간',
      '퇴근시간': '퇴근시간',
      '출근': '출근',
      '결근': '결근',
      '휴무': '휴무',
      '급여명세서': '급여명세서',
      '확인': '확인',
      '취소': '취소',
      '급여': '급여',
      '확인 완료': '확인 완료',
      'PDF 다운': 'PDF 다운',
      '월    급여명세서': '월    급여명세서',
      '급여명세서의 해당 월에\n급여 정보에 문제가 없는지\n확인하였습니까?': '급여명세서의 해당 월에\n급여 정보에 문제가 없는지\n확인하였습니까?',
      '확인 버튼을 클릭하면 수정이 불가능합니다': '확인 버튼을 클릭하면 수정이 불가능합니다',
      '님의 근로명세서': '님의 근로명세서',
      '해당 근로자의 출결 사항을 저장하시겠습니까?': '해당 근로자의 출결 사항을 저장하시겠습니까?',
      '최종 선택한 내용으로 표시됩니다': '최종 선택한 내용으로 표시됩니다',
      '총 근무시간': '총 근무시간',
      ' 시간': ' 시간',
      ' 원': ' 원',
      '경기도':'경기도',
      '강원도':'강원도',
      '충청북도':'충청북도',
      '충청남도':'충청남도',
      '경상북도':'경상북도',
      '경상남도':'경상남도',
      '전라북도':'전라북도',
      '전라남도':'전라남도',
      '제주도':'제주도',
      '회사명':'회사명',
      '내정보':'내정보',
      '카메라':'카메라',
      '채팅':'채팅',
      '회원을 탈퇴하시겠습니까?':'Would you like to cancel your membership?',
      '탈퇴':'cancel membership',
      '변경되었습니다 다시 로그인해주세요':'변경되었습니다 다시 로그인해주세요',
      '변경 실패 했습니다':'변경 실패 했습니다',
      '승인이 필요합니다':'승인이 필요합니다',
      '로그인 실패':'로그인 실패',
      '회원탈퇴 실패':'회원탈퇴 실패',
      '날짜를 다시확인해주세요':'날짜를 다시확인해주세요',
      '저장 실패':'저장 실패',
      '제목을 기입해주세요':'제목을 기입해주세요',
      '내용을 기입해주세요':'내용을 기입해주세요',
      '성공':'성공',
      '이름을 기입해주세요':'이름을 기입해주세요',
      '비밀번호를 기입해주세요':'비밀번호를 기입해주세요',
      '직책을 기입해주세요':'직책을 기입해주세요',
      '핸드폰을 인증해주세요':'핸드폰을 인증해주세요',
      '출,입국일을 기입해주세요':'출,입국일을 기입해주세요',
      '이메일을 확인해주세요':'이메일을 확인해주세요',
      '회원가입 성공':'회원가입 성공',
      '회원가입 실패':'회원가입 실패',
      '근로자 상세정보':'근로자 상세정보',
      '회원 탈퇴':'회원 탈퇴',
      '근무지':'근무지'
    },
    'en_US': {
      '로그인': 'login',
      '회원가입': 'singUp',
      '관리자': 'admin',
      '내정보':'My Info',
      '회사명':'Company Name',
      '고용주': 'Employer',
      '이메일':'Email',
      '근로자': 'Worker',
      '아이디': 'ID',
      '비밀번호': 'password',
      '본인인증': 'Check phone number',
      '휴대폰 번호': 'Phone number',
      '인증번호 발송': 'Send code',
      '인증 완료': 'Complete',
      '관리자 회원가입': 'Admin signup',
      '이름': 'Name',
      '생년월일': 'Date of birth',
      '휴대폰 번호(ID)': 'Phone number(ID)',
      '직책': 'position',
      '가입하기': 'Sign up',
      '고용주 회원가입': 'Employer signup',
      '사업장 위치': 'Company address',
      '업장명(상호)': 'Company name',
      '근로자 회원가입': 'Worker signup',
      '이메일(ID)': 'E-mail(ID)',
      '성별': 'Gender',
      '남성': 'male',
      '여성': 'female',
      '국적': 'Nationality',
      '입국일': 'Date of arrival',
      '출국일': 'departure date',
      '공지사항': 'Notice',
      '지역별 공지사항': 'Regional Announcement',
      '홈': 'Home',
      '로그인/아웃': 'login/out',
      '회사 소개': 'Company info',
      '홈으로': 'Home',
      '조직 구성': 'Organization',
      '출퇴근 QR코드': 'Commute QRcode',
      '전체 공지사항': 'Full notice',
      '댓글': 'Comments',
      '제보하기': 'Report',
      '제목': 'title',
      '내용': 'content',
      '완료': 'complete',
      '제보 글 작성': 'Writing a report',
      '메세지': 'Message',
      '대화상대 초대': 'Invite interlocutors',
      '필리핀 식품': 'philippines food',
      '교육 정보': 'Education',
      '비자 안내': 'visa guide',
      '법률 상담': 'legal counsel',
      '도움 전화': 'Helpline',
      '필리핀 송금': 'Philippine remittance',
      '내 정보': 'My information',
      '내 정보 수정': 'Edit my info',
      '근로자 정보': 'Workers info',
      '고용주 정보': 'Employer',
      '근로자 상세정보':'worker details',
      '출퇴근 현황': 'Commuting status',
      '급여 현황': 'Salary status',
      '나의 상세 정보': 'My details',
      '출근시간': 'attendance hour',
      '퇴근시간': 'leave hour',
      '출근': 'Attendance',
      '결근': 'absence',
      '휴무': 'Holiday',
      '확인': 'OK',
      '취소': 'cancel',
      '급여': 'Salary',
      '확인 완료': 'Complete',
      'PDF 다운': 'Download PDF',
      '급여명세서의 해당 월에\n급여 정보에 문제가 없는지\n확인하였습니까?': 'Did you check if there is no problem with the salary information in that month on the salary statement?',
      '확인 버튼을 클릭하면 수정이 불가능합니다': 'If you click the OK button, the modification is not possible.',
      '님의 근로명세서': "s' paystub",
      '월    급여명세서': 'Month',
      '해당 근로자의 출결 사항을 저장하시겠습니까?': 'Do you want to save the attendance of that worker?',
      '최종 선택한 내용으로 표시됩니다': 'It will be displayed as the final selection',
      '총 근무시간': 'Total hours',
      ' 시간': ' .H',
      '근무지':'work place',
      ' 원': ' won',
      '경기도':'gyeonggi-do',
      '강원도':'Gangwon-do',
      '충청북도':'Chung-cheong bukdo',
      '충청남도':'Chungcheongnam-do',
      '경상북도':'Gyeongsangbuk-do',
      '경상남도':'Gyeongsangnam-do',
      '전라북도':'Jeollabuk do',
      '전라남도':'Jeollanam-do',
      '제주도':'jeju island',
      '카메라':'camera',
      '채팅':'chat',
      '남자':'male',
      '여자':'female',
      '회원을 탈퇴하시겠습니까?':'Would you like to cancel your membership?',
      '변경되었습니다 다시 로그인해주세요':"It's been changed. Please log in again",
      '변경 실패 했습니다':'Failed to change it',
      '승인이 필요합니다':'Need approval',
      '로그인 실패':'Login Failed',
      '회원탈퇴 실패':'Failed to withdraw from membership',
      '날짜를 다시확인해주세요':'Please check the date again',
      '저장 실패':'Save failed',
      '제목을 기입해주세요':'Please write down the title',
      '내용을 기입해주세요':'Please fill it out',
      '성공':'Success',
      '이름을 기입해주세요':'Please write your name',
      '비밀번호를 기입해주세요':'Please enter your password',
      '직책을 기입해주세요':'Please fill out your position',
      '핸드폰을 인증해주세요':'Please verify your phone',
      '출,입국일을 기입해주세요':'Please fill out your departure and arrival dates',
      '이메일을 확인해주세요':'Please check your email',
      '회원가입 성공':'Successful membership registration',
      '회원가입 실패':'Failed to sign up for membership',
      '회원 탈퇴':'Withdrawal',
    },
  };
}


